baseurl      = "http://www.markmyjourney.com/"
languageCode = "en-us"
title        = "MarkMyJourney"

disableRSS     = true
disableSitemap = true

paginate = 5

[permalinks]
  blog = "/:slug"

[taxonomies]
  destination = "destinations"