baseurl      = "http://www.markmyjourney.com/"
languageCode = "en-us"
title        = "MarkMyJourney"

disableRSS     = true
disableSitemap = true

paginate = 3

[permalinks]
  blog = "/:title"

[taxonomies]
  destination = "destinations"