baseurl      = "https://www.markmyjourney.com/"
languageCode = "en-us"
title        = "MarkMyJourney"

disableRSS     = true
disableSitemap = true
paginate       = 5
SectionPagesMenu = "main"

[blackfriday]
  fractions = false

[permalinks]
  blog = "/:slug/"

[taxonomies]
  destination = "destinations"