baseurl      = "https://www.markmyjourney.com/"
languageCode = "en-us"
title        = "MarkMyJourney"

disableHugoGeneratorInject = true
disableRSS      = true
disableSitemap  = true
enableRobotsTXT = true
paginate        = 5
pluralizeListTitles = false
SectionPagesMenu = "main"

[blackfriday]
  fractions = false

[[menu.social]]
  name   = "E-mail"
  identifier = "email"
  url    = "mailto:mark@markmyjourney.com"
  weight = 100
[[menu.social]]
  name = "GitHub"
  url  = "https://github.com/vseventer"
[[menu.social]]
  name = "LinkedIn"
  url  = "https://www.linkedin.com/in/markvanseventer"
[[menu.social]]
  name = "Twitter"
  url  = "https://twitter.com/vseventer"

[permalinks]
  blog = "/:slug/"

[taxonomies]
  destination = "destinations"